replicaCount: 1

image:
  repository: travel-flights
  tag: v1.0.6
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 9080

container:
  port: 9080
  env:
    PORT: "9080"

namespace: travel-flights-lab

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  readiness:
    path: /healthz
    initialDelaySeconds: 3
    periodSeconds: 10
  liveness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 15
