apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: travel-flights
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saratrajan/dora-metrics
    targetRevision: main
    path: apps/travel-flights/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: travel-flights-lab
  syncPolicy:
    syncOptions:
      - CreateNamespace=true